name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Python and PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: "3.12"
          cache: true

      - name: Install Dependencies
        run: pdm install --dev

      - name: Run Tests
        run: pdm run pytest --tb=short

  publish:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Python and PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: "3.12"
          cache: true

      - name: Build Package
        run: pdm build

      - name: Publish to TestPyPI
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: pdm publish --repository testpypi

      - name: Publish to PyPI
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: pdm publish
