name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v3
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pdm install
      - name: Run tests
        run: pdm run pytest --tb=short
